{{ $worker_replicas := 0 }}
{{ $master_replicas := 0 }}
{{ range .Values.hosts }}
    {{ if eq .role "worker" }}
        {{ $worker_replicas = add $worker_replicas 1 }}
    {{ else }}
        {{ $master_replicas = add $master_replicas 1 }}
    {{ end }}
{{ end }}
apiVersion: v1
baseDomain: {{ .Values.domain }}
metadata:
  name: {{ .Values.clustername }}
proxy:
  httpProxy: {{ .Values.proxy }}
  httpsProxy: {{ .Values.proxy }}
  noProxy: {{ .Values.no_proxy }}
compute:
  - name: worker
    replicas: {{ $worker_replicas }}
controlPlane:
  name: master
  replicas: {{ $master_replicas }}
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: {{ .Values.network }}
  serviceNetwork:
    - 172.30.0.0/16
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
platform:
  none: {}
fips: false
pullSecret: '{{ .Files.Get "pull-secret" }}'
sshKey: {{ .Files.Get "sshkey.pub" }}
